### ISSUE TITLE
Remove .exe files from repository

### ISSUE THREAD

**Issue by TeeSlayer** [TwChilli/chilli-server#3]
Just add the file extension to .gitignore

**Comment by ChillerDragon** [comment]
closed by https://github.com/TwChilli/chilli-server/commit/76bbf2b0cf777d216b984f1d21b2588061b01d01

**Comment by TeeSlayer** [comment]
You still need to git rm everything and re-add how you usually do.

**Comment by ChillerDragon** [comment]
I guess fokko needs some of the binarys
